### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by VasilisKos** [SecUSo/privacy-friendly-2048#16]
A dark theme of the app would be very convenient, and appreciated.

**Comment by StormyIceLeopard** [comment]
Dark theme would be appreciated.

**Comment by deifyed** [comment]
I'm working on dark mode [here](https://github.com/deifyed/privacy-friendly-2048/tree/feature/master/darkmode). It's not ready yet, but if you know how to build it it works

**Comment by vishalscodes** [comment]
Yep, only reason why I didn't fully switch.

**Comment by CheeseFort** [comment]
+1

**Comment by KaKi87** [comment]
Hi @udenr,
Any news on this and getting the PR merged ?
Thanks

**Comment by KaKi87** [comment]
Thanks, I'm looking forward to a new release :)
