### ISSUE TITLE
fdroid metadata consistency

### ISSUE THREAD

**Issue by ghost** [SecUSo/privacy-friendly-2048#22]
@petermayer @Kamuno 
```
AuthorName: SECUSO - Security Usability Society
AuthorEmail: contact@secuso.org
AuthorWebSite: https://secuso.aifb.kit.edu/english/
WebSite: app specific URL from https://secuso.aifb.kit.edu/english/105.php
```
* **your explicit consent is required** to add AuthorEmail and AuthorWebSite incomplete in fdroid metadata for all apps
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by udenr** [comment]
We consent to updating the information for all our apps.
If possible, we would use the email address pfa@secuso.org
