### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [SecUSo/privacy-friendly-2048#23]
https://hosted.weblate.org/projects/privacy-friendly-2048/#information
says GPLv3-only,
whereas
https://github.com/search?q=repo%3ASecUSo%2Fprivacy-friendly-2048%20any%20later&type=code
says GPLv3-or-later.

It can be changed in

https://hosted.weblate.org/settings/privacy-friendly-2048/android-app/
https://hosted.weblate.org/settings/privacy-friendly-2048/glossary/

**Comment by udenr** [comment]
Thanks for pointing it out. It's updated now. We are currently in the process of testing how we can use Weblate for our projects.
