### ISSUE TITLE
Wrong change log (F-Drodi)

### ISSUE THREAD

**Issue by NeroRome** [SecUSo/privacy-friendly-2048#8]
I've currently installed the latest version from F-Droid (v1.2, 2019-03-31).

The link to the change log (https://github.com/SecUSo/privacy-friendly-2048/blob/HEAD/CHANGELOG.md) in F-Droid ("Verweise" / "Änderungen) is dissonant. 
The latest version in this document is "Version 2.2.2 (2017-10-16)". ?!?
_"v1.2"_ in F-Droid but _"Version 2.2.2"_ (with a date of year 2017) in CHANGELOG.md is rubbish.

**Comment by petermayer** [comment]
Hey, thanks for reporting this. It seems the CHANGELOG.md was not reset before the initial commit based on the our PFA template.
